########################################
## Custom models
########################################
Model\Token:
  itemOperations: []
  collectionOperations:
    post_auth_token_exchange:
      method: 'POST'
      path: '/token/exchange'
      route_name: 'post_auth_token_exchange'
      swagger_context:
        consumes:
          - 'application/x-www-form-urlencoded'
        produces:
          - 'application/json'
        tags:
          - Auth
        parameters:
          - name: token
            in: formData
            type: string
            required: true
            description: 'Platform admin token'
          - name: username
            in: formData
            type: string
            required: false
            description: 'Target brand admin user name'
          - name: brandId
            in: formData
            type: integer
            required: false
            description: 'Target brand ID'

Model\ActiveCalls:
  itemOperations:
    get_my_active_calls:
      access_control: '"ROLE_BRAND_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'GET'
      path: '/my/active_calls'
      route_name: 'get_my_active_calls'
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
        parameters:
        - name: company
          in: query
          type: integer
          required: false
          description: 'Company Id'
  collectionOperations: []

Model\UsersMassImport:
  itemOperations: []
  collectionOperations:
    post_users_mass_import:
      access_control: '"ROLE_BRAND_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'POST'
      path: '/users/mass_import'
      route_name: 'post_users_mass_import'
      swagger_context:
        consumes:
          - 'multipart/form-data'
        produces:
          - 'application/json'
        tags:
          - Provider
        parameters:
          - name: company
            in: formData
            type: integer
            required: true
            description: 'Company Id'
          - name: csv
            in: formData
            type: file
            required: true
            description: "*name, *lastname, email, terminal name,terminal password, terminal model, mac, extension, ddi country, ddi number, ddi provider"

Model\RegistrationSummary:
  itemOperations:
    get_my_registration_summary:
      access_control: '"ROLE_BRAND_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'GET'
      path: '/my/registration_summary'
      route_name: 'get_my_registration_summary'
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
        parameters:
        - name: company
          in: query
          type: integer
          required: false
          description: 'Company Id'
  collectionOperations: []

Model\Profile:
  itemOperations:
    get_my_profile:
      access_control: '"ROLE_BRAND_ADMIN" in roles'
      depth: 2
      method: 'GET'
      path: '/my/profile'
      route_name: 'get_my_profile'
      swagger_context:
        produces:
          - 'application/json'
        tags:
          - My
        parameters: []
  collectionOperations: []
